#!/usr/bin/env python3
"""Send the daily AI newsletter digest to configured channels.

Channels (each is enabled only when its environment variables are set):

  Email (Resend):   RESEND_API_KEY, NEWSLETTER_FROM, NEWSLETTER_TO
                    + optional NEWSLETTER_SUBSCRIBERS (comma-separated extra recipients)
  Telegram:         TELEGRAM_BOT_TOKEN, TELEGRAM_CHAT_ID

Usage:
  python3 scripts/send_digest.py            # send to every configured channel
  python3 scripts/send_digest.py --dry-run  # build the digests, print, don't send

Channels with missing credentials are skipped with a note, so the daily
workflow stays green while a channel is still being configured.
"""

import argparse
import html
import json
import os
import sys
from datetime import datetime, timezone
from pathlib import Path

import httpx

ROOT = Path(__file__).parent.parent
DATA_FILE = ROOT / "data" / "newsletter.json"

EMAIL_PER_CATEGORY = 4   # top stories per category in the email
TELEGRAM_TOTAL = 6       # total stories in the Telegram message

CATEGORY_ORDER = ["breaking", "research", "industry", "tools"]
CATEGORY_LABELS = {
    "breaking": "🔥 Breaking News",
    "research": "📄 Research Papers",
    "industry": "🏢 Industry",
    "tools": "🛠️ Tools & Releases",
}
CATEGORY_EMOJI = {"breaking": "🔥", "research": "📄", "industry": "🏢", "tools": "🛠️"}


def load_digest():
    if not DATA_FILE.exists():
        raise SystemExit(f"❌ {DATA_FILE} not found — run the fetcher first")
    data = json.loads(DATA_FILE.read_text(encoding="utf-8"))
    articles = data.get("all_articles", [])
    if not articles:
        raise SystemExit("ℹ No articles in newsletter.json — nothing to send")
    return data


def build_stories(data, per_category=EMAIL_PER_CATEGORY):
    cats = data.get("categories", {})
    stories = []
    for cat in CATEGORY_ORDER:
        for a in (cats.get(cat) or [])[:per_category]:
            stories.append((cat, a))
    return stories


def fmt_summary(a):
    s = (a.get("summary") or "").strip()
    if len(s) > 220:
        s = s[:217].rstrip() + "…"
    return s


def build_html(stories, data):
    generated = data.get("generated_at", "")
    try:
        date_str = datetime.fromisoformat(generated).strftime("%A, %B %d, %Y")
    except Exception:
        date_str = generated[:10]

    cards = []
    for cat, a in stories:
        title = html.escape(a.get("title", ""))
        url = html.escape(a.get("url", "#"))
        source = html.escape(a.get("source", ""))
        summary = html.escape(fmt_summary(a))
        cards.append(f"""
      <div style="margin:0 0 16px;padding:16px 18px;border:1px solid #e4e4e7;border-radius:12px;background:#ffffff;">
        <div style="font-size:11px;font-weight:600;letter-spacing:.4px;text-transform:uppercase;color:#7c3aed;margin-bottom:6px;">{CATEGORY_LABELS.get(cat, cat)} · {source}</div>
        <a href="{url}" style="font-size:15px;font-weight:600;color:#18181b;text-decoration:none;line-height:1.35;">{title}</a>
        <p style="font-size:13px;color:#52525b;line-height:1.5;margin:6px 0 0;">{summary}</p>
      </div>""")

    return f"""<!DOCTYPE html>
<html>
<body style="margin:0;padding:0;background:#f4f4f5;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',Roboto,Helvetica,Arial,sans-serif;">
  <div style="max-width:640px;margin:0 auto;padding:24px 16px;">
    <div style="text-align:center;padding:28px 20px;background:linear-gradient(135deg,#111827,#1e1b4b);border-radius:16px;color:#fff;">
      <div style="font-size:22px;font-weight:700;">🤖 AI Daily Briefing</div>
      <div style="font-size:13px;color:#a5b4fc;margin-top:6px;">{date_str} · {data.get('article_count', 0)} stories collected</div>
    </div>
    <div style="background:#fff;border-radius:16px;padding:20px;margin-top:16px;">
      {''.join(cards)}
    </div>
    <p style="text-align:center;font-size:11px;color:#71717a;margin-top:16px;">
      Generated by <strong>AI News Update</strong> · <a href="https://github.com/DavidGaso1/AI-News-Update" style="color:#71717a;">View the full newsletter</a>
    </p>
  </div>
</body>
</html>"""


def build_text(stories, data):
    generated = data.get("generated_at", "")
    try:
        date_str = datetime.fromisoformat(generated).strftime("%A, %B %d, %Y")
    except Exception:
        date_str = generated[:10]

    lines = [f"🤖 AI Daily Briefing — {date_str}", f"{data.get('article_count', 0)} stories collected", "=" * 40]
    for cat, a in stories:
        lines.append("")
        lines.append(f"{CATEGORY_EMOJI.get(cat, '•')} [{a.get('source', '')}] {a.get('title', '')}")
        s = fmt_summary(a)
        if s:
            lines.append(f"   {s}")
        lines.append(f"   {a.get('url', '')}")
    lines.append("")
    lines.append("Full newsletter: https://github.com/DavidGaso1/AI-News-Update")
    return "\n".join(lines)


def build_telegram(data, total=TELEGRAM_TOTAL):
    """Compact Telegram message: top N stories across all categories."""
    cats = data.get("categories", {})
    flat = []
    for cat in CATEGORY_ORDER:
        for a in (cats.get(cat) or []):
            flat.append((cat, a))
    flat.sort(key=lambda x: x[1].get("published_at", ""), reverse=True)

    generated = data.get("generated_at", "")
    try:
        date_str = datetime.fromisoformat(generated).strftime("%b %d, %Y")
    except Exception:
        date_str = generated[:10]

    lines = [f"<b>🤖 AI Daily Briefing — {date_str}</b>", ""]
    for cat, a in flat[:total]:
        # Truncate BEFORE escaping so an HTML entity is never split mid-way
        # (Telegram's HTML parser rejects a truncated entity with HTTP 400).
        title = html.escape(a.get("title", "")[:170])
        source = html.escape(a.get("source", ""))
        url = html.escape(a.get("url", "#"))
        lines.append(f"{CATEGORY_EMOJI.get(cat, '•')} <a href=\"{url}\">{title}</a>")
        lines.append(f"<i>{source}</i>")
        lines.append("")
    lines.append("<a href=\"https://github.com/DavidGaso1/AI-News-Update\">Full newsletter →</a>")
    return "\n".join(lines)


def parse_recipients(raw):
    """Split a comma-separated recipient list, dropping empties/duplicates."""
    return list(dict.fromkeys(r.strip() for r in (raw or "").split(",") if r.strip()))


def send_resend(subject, html_body, text_body):
    api_key = os.environ.get("RESEND_API_KEY")
    frm = os.environ.get("NEWSLETTER_FROM")
    to = list(dict.fromkeys(
        parse_recipients(os.environ.get("NEWSLETTER_TO")) + parse_recipients(os.environ.get("NEWSLETTER_SUBSCRIBERS"))
    ))
    if not (api_key and frm and to):
        print("ℹ Email channel not configured (RESEND_API_KEY / NEWSLETTER_FROM / NEWSLETTER_TO) — skipping")
        return False
    payload = {
        "from": frm,
        "to": to,
        "subject": subject,
        "html": html_body,
        "text": text_body,
    }
    try:
        resp = httpx.post(
            "https://api.resend.com/emails",
            json=payload,
            headers={"Authorization": f"Bearer {api_key}"},
            timeout=30.0,
        )
    except httpx.HTTPError as e:
        print(f"❌ Email failed (network): {e}")
        return False
    if resp.status_code in (200, 201):
        print(f"✅ Email sent to {', '.join(to)} (id {resp.json().get('id', '?')})")
        return True
    print(f"❌ Email failed ({resp.status_code}): {resp.text[:300]}")
    return False


def send_telegram(message):
    token = os.environ.get("TELEGRAM_BOT_TOKEN")
    chat_id = os.environ.get("TELEGRAM_CHAT_ID")
    if not (token and chat_id):
        print("ℹ Telegram channel not configured (TELEGRAM_BOT_TOKEN / TELEGRAM_CHAT_ID) — skipping")
        return False
    try:
        resp = httpx.post(
            f"https://api.telegram.org/bot{token}/sendMessage",
            json={"chat_id": chat_id, "text": message, "parse_mode": "HTML", "disable_web_page_preview": True},
            timeout=30.0,
        )
    except httpx.HTTPError as e:
        print(f"❌ Telegram failed (network): {e}")
        return False
    if resp.status_code == 200:
        print(f"✅ Telegram message sent to chat {chat_id}")
        return True
    print(f"❌ Telegram failed ({resp.status_code}): {resp.text[:300]}")
    return False


def main():
    parser = argparse.ArgumentParser(description="Send the daily AI newsletter digest")
    parser.add_argument("--dry-run", action="store_true", help="build and print the digests without sending")
    parser.add_argument("--telegram-only", action="store_true", help="only send the Telegram message")
    args = parser.parse_args()

    data = load_digest()
    stories = build_stories(data)
    if not stories:
        print("ℹ No stories to send")
        return 0

    generated = data.get("generated_at", "")
    try:
        subject = f"🤖 AI Daily Briefing — {datetime.fromisoformat(generated).strftime('%b %d, %Y')}"
    except Exception:
        subject = f"🤖 AI Daily Briefing — {datetime.now(timezone.utc).strftime('%b %d, %Y')}"

    if args.dry_run:
        print("=" * 60)
        print("DRY RUN — nothing will be sent")
        print("=" * 60)
        print("\n--- EMAIL SUBJECT:", subject)
        print("--- EMAIL HTML (first 600 chars):")
        print(build_html(stories, data)[:600], "...")
        print("\n--- EMAIL TEXT:")
        print(build_text(stories, data))
        print("\n--- TELEGRAM MESSAGE:")
        print(build_telegram(data))
        return 0

    ok = 0
    if not args.telegram_only:
        ok += int(send_resend(subject, build_html(stories, data), build_text(stories, data)))
    ok += int(send_telegram(build_telegram(data)))
    return 0 if ok > 0 or not any(
        os.environ.get(k) for k in ("RESEND_API_KEY", "TELEGRAM_BOT_TOKEN")
    ) else 1


if __name__ == "__main__":
    sys.exit(main())
